name: Tests

on:
  push:
    paths:
      - 'Experimentation/site/**'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - 'Experimentation/site/**'
      - '.github/workflows/tests.yml'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install causalpy dash dash-bootstrap-components pandas numpy plotly pytest

      - name: Run pytest
        run: pytest Experimentation/site/tests
